services:
  app:
    container_name: fleet_manager_Veloe

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fleetdb

    depends_on:
      - db

    networks:
      - fleetnet

  db:
    image: postgres:15-alpine

    container_name: postgres_fleet

    restart: always

    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: fleetdb

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - fleetnet

networks:
  fleetnet:
    driver: bridge

volumes:
  db_data: