spring:
  datasource:
    url: jdb:postgresql://localhost:5432/fleet_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpe:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dealect: org.hibernate.dialect.PostgresSQLDialect

  sql:
    init:
      mode: always

  server:
    port: 8080
    servlet:
      context-path: /fleet-manager

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method

  logging:
    level:
      com.veloe.fleet: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBlinder: TRACE