name: CI/CD - Fleet Manager Veloe

on:
  push:
    branches:
      - "main"
    pull_request:
      branches:
        - "main"

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: Admin
          POSTGRES_PASSWORD: Admin
          POSTGRES_DB: fleetdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U Admin -d fleetdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Instalando dependências e compilar
        run: mvn clean compile -DskipTests

      - name: Rodar testes
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/fleetdb
          SPRING_DATASOURCE_USERNAME: Admin
          SPRING_DATASOURCE_PASSWORD: Admin
        run: mvn test

  sonar:
    name: Análise de qualidade (sonarCloud)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check do Código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Análise no Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar \
          -Dsonar.projectKey=WMB25_Fleet_manager-Veloe \
          -Dsonar.organization=wmb25 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker:
    name: Build e push imagem Docker
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login no Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build imagem
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/Fleet_manager-Veloe:latest .

      - name: Push para DockerHub
        run: docker push ${{ vars.DOCKER_USERNAME }}/Fleet_manager-Veloe:latest